//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlow.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceErrorMessage_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessage_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashFlow.Exception.ResourceErrorMessage.es", typeof(ResourceErrorMessage_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail o contraseña incorrectos.
        /// </summary>
        internal static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El importe debe ser mayor que cero..
        /// </summary>
        internal static string EXPENSE_AMOUNT_MUST_BE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("EXPENSE_AMOUNT_MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha no puede estar en el futuro..
        /// </summary>
        internal static string EXPENSE_DATE_CANNOT_BE_IN_THE_FUTURE {
            get {
                return ResourceManager.GetString("EXPENSE_DATE_CANNOT_BE_IN_THE_FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha es obligatoria..
        /// </summary>
        internal static string EXPENSE_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("EXPENSE_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción no puede superar los 1000 caracteres..
        /// </summary>
        internal static string EXPENSE_DESCRIPTION_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("EXPENSE_DESCRIPTION_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto no encontrado..
        /// </summary>
        internal static string EXPENSE_NOT_FOUND {
            get {
                return ResourceManager.GetString("EXPENSE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de pago informado no es válido..
        /// </summary>
        internal static string EXPENSE_PAYMENT_TYPE_INVALID {
            get {
                return ResourceManager.GetString("EXPENSE_PAYMENT_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El título no puede superar los 100 caracteres..
        /// </summary>
        internal static string EXPENSE_TITLE_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("EXPENSE_TITLE_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El título es obligatorio..
        /// </summary>
        internal static string EXPENSE_TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("EXPENSE_TITLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este e-mail ya está registrado..
        /// </summary>
        internal static string USER_EMAIL_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("USER_EMAIL.ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El e-mail es obligatorio..
        /// </summary>
        internal static string USER_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("USER_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El e-mail informado no es válido..
        /// </summary>
        internal static string USER_EMAIL_VALID {
            get {
                return ResourceManager.GetString("USER_EMAIL_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre debe tener al menos 3 caracteres..
        /// </summary>
        internal static string USER_NAME_MINIMUM_LENGTH {
            get {
                return ResourceManager.GetString("USER_NAME_MINIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es obligatorio..
        /// </summary>
        internal static string USER_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("USER_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener al menos 8 caracteres..
        /// </summary>
        internal static string USER_PASSWORD_MINIMUM_LENGTH {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MINIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe contener al menos una letra minúscula..
        /// </summary>
        internal static string USER_PASSWORD_MUST_CONTAIN_LOWERCASE_LETTER {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MUST_CONTAIN_LOWERCASE_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe contener al menos un número..
        /// </summary>
        internal static string USER_PASSWORD_MUST_CONTAIN_NUMBER {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MUST_CONTAIN_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe contener al menos un carácter especial..
        /// </summary>
        internal static string USER_PASSWORD_MUST_CONTAIN_SPECIAL_CHARACTER {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MUST_CONTAIN_SPECIAL_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe contener al menos una letra mayúscula..
        /// </summary>
        internal static string USER_PASSWORD_MUST_CONTAIN_UPPERCASE_LETTER {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MUST_CONTAIN_UPPERCASE_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es obligatoria..
        /// </summary>
        internal static string USER_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("USER_PASSWORD_REQUIRED", resourceCulture);
            }
        }
    }
}
