//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlow.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceErrorMessage_pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessage_pt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashFlow.Exception.ResourceErrorMessage.pt", typeof(ResourceErrorMessage_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor deve ser maior que zero..
        /// </summary>
        internal static string EXPENSE_AMOUNT_MUST_BE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("EXPENSE_AMOUNT_MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data não pode ser futura..
        /// </summary>
        internal static string EXPENSE_DATE_CANNOT_BE_IN_THE_FUTURE {
            get {
                return ResourceManager.GetString("EXPENSE_DATE_CANNOT_BE_IN_THE_FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data é obrigatória..
        /// </summary>
        internal static string EXPENSE_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("EXPENSE_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição não pode ter mais que 1000 caracteres..
        /// </summary>
        internal static string EXPENSE_DESCRIPTION_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("EXPENSE_DESCRIPTION_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de pagamento informado é inválido..
        /// </summary>
        internal static string EXPENSE_PAYMENT_TYPE_INVALID {
            get {
                return ResourceManager.GetString("EXPENSE_PAYMENT_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título não pode ter mais que 100 caracteres..
        /// </summary>
        internal static string EXPENSE_TITLE_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("EXPENSE_TITLE_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título é obrigatório..
        /// </summary>
        internal static string EXPENSE_TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("EXPENSE_TITLE_REQUIRED", resourceCulture);
            }
        }
    }
}
