//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlow.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceErrorMessage_pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessage_pt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashFlow.Exception.ResourceErrorMessage.pt", typeof(ResourceErrorMessage_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria já registrada..
        /// </summary>
        internal static string CATEGORY_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("CATEGORY_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cor não pode ter mais que 20 caracteres..
        /// </summary>
        internal static string CATEGORY_COLOR_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("CATEGORY_COLOR_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cor é obrigatória..
        /// </summary>
        internal static string CATEGORY_COLOR_REQUIRED {
            get {
                return ResourceManager.GetString("CATEGORY_COLOR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição não pode ter mais que 1000 caracteres..
        /// </summary>
        internal static string CATEGORY_DESCRIPTION_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("CATEGORY_DESCRIPTION_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma meta para esta categoria..
        /// </summary>
        internal static string CATEGORY_GOAL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("CATEGORY_GOAL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O mês informado é inválido..
        /// </summary>
        internal static string CATEGORY_GOAL_MONTH_INVALID {
            get {
                return ResourceManager.GetString("CATEGORY_GOAL_MONTH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta da categoria não encontrada..
        /// </summary>
        internal static string CATEGORY_GOAL_NOT_FOUND {
            get {
                return ResourceManager.GetString("CATEGORY_GOAL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor da meta deve ser maior que zero..
        /// </summary>
        internal static string CATEGORY_GOAL_TARGET_AMOUNT_MUST_BE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("CATEGORY_GOAL_TARGET_AMOUNT_MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ano informado é inválido..
        /// </summary>
        internal static string CATEGORY_GOAL_YEAR_INVALID {
            get {
                return ResourceManager.GetString("CATEGORY_GOAL_YEAR_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id da categoria é obrigatório..
        /// </summary>
        internal static string CATEGORY_ID_REQUIRED {
            get {
                return ResourceManager.GetString("CATEGORY_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ter mais que 100 caracteres..
        /// </summary>
        internal static string CATEGORY_NAME_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("CATEGORY_NAME_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        internal static string CATEGORY_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("CATEGORY_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria não encontrada..
        /// </summary>
        internal static string CATEGORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CATEGORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo da categoria informado é inválido..
        /// </summary>
        internal static string CATEGORY_TYPE_INVALID {
            get {
                return ResourceManager.GetString("CATEGORY_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou senha inválidos..
        /// </summary>
        internal static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor deve ser maior que zero..
        /// </summary>
        internal static string EXPENSE_AMOUNT_MUST_BE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("EXPENSE_AMOUNT_MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data não pode ser futura..
        /// </summary>
        internal static string EXPENSE_DATE_CANNOT_BE_IN_THE_FUTURE {
            get {
                return ResourceManager.GetString("EXPENSE_DATE_CANNOT_BE_IN_THE_FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data é obrigatória..
        /// </summary>
        internal static string EXPENSE_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("EXPENSE_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição não pode ter mais que 1000 caracteres..
        /// </summary>
        internal static string EXPENSE_DESCRIPTION_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("EXPENSE_DESCRIPTION_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despesa não encontrada..
        /// </summary>
        internal static string EXPENSE_NOT_FOUND {
            get {
                return ResourceManager.GetString("EXPENSE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de pagamento informado é inválido..
        /// </summary>
        internal static string EXPENSE_PAYMENT_TYPE_INVALID {
            get {
                return ResourceManager.GetString("EXPENSE_PAYMENT_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título não pode ter mais que 100 caracteres..
        /// </summary>
        internal static string EXPENSE_TITLE_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("EXPENSE_TITLE_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título é obrigatório..
        /// </summary>
        internal static string EXPENSE_TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("EXPENSE_TITLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor deve ser maior que zero..
        /// </summary>
        internal static string INCOME_AMOUNT_MUST_BE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("INCOME_AMOUNT_MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data não pode ser futura..
        /// </summary>
        internal static string INCOME_DATE_CANNOT_BE_IN_THE_FUTURE {
            get {
                return ResourceManager.GetString("INCOME_DATE_CANNOT_BE_IN_THE_FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data é obrigatória..
        /// </summary>
        internal static string INCOME_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("INCOME_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição não pode ter mais que 1000 caracteres..
        /// </summary>
        internal static string INCOME_DESCRIPTION_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("INCOME_DESCRIPTION_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receita não encontrada..
        /// </summary>
        internal static string INCOME_NOT_FOUND {
            get {
                return ResourceManager.GetString("INCOME_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título não pode ter mais que 100 caracteres..
        /// </summary>
        internal static string INCOME_TITLE_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("INCOME_TITLE_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título é obrigatório..
        /// </summary>
        internal static string INCOME_TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("INCOME_TITLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atual está incorreta..
        /// </summary>
        internal static string OLD_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("OLD_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        internal static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este e-mail já foi registrado..
        /// </summary>
        internal static string USER_EMAIL_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("USER_EMAIL.ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório..
        /// </summary>
        internal static string USER_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("USER_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado não é válido..
        /// </summary>
        internal static string USER_EMAIL_VALID {
            get {
                return ResourceManager.GetString("USER_EMAIL_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve ter pelo menos 3 caracteres..
        /// </summary>
        internal static string USER_NAME_MINIMUM_LENGTH {
            get {
                return ResourceManager.GetString("USER_NAME_MINIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        internal static string USER_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("USER_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter pelo menos 8 caracteres..
        /// </summary>
        internal static string USER_PASSWORD_MINIMUM_LENGTH {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MINIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos uma letra minúscula..
        /// </summary>
        internal static string USER_PASSWORD_MUST_CONTAIN_LOWERCASE_LETTER {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MUST_CONTAIN_LOWERCASE_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos um número..
        /// </summary>
        internal static string USER_PASSWORD_MUST_CONTAIN_NUMBER {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MUST_CONTAIN_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos um caractere especial..
        /// </summary>
        internal static string USER_PASSWORD_MUST_CONTAIN_SPECIAL_CHARACTER {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MUST_CONTAIN_SPECIAL_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos uma letra maiúscula..
        /// </summary>
        internal static string USER_PASSWORD_MUST_CONTAIN_UPPERCASE_LETTER {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MUST_CONTAIN_UPPERCASE_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória..
        /// </summary>
        internal static string USER_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("USER_PASSWORD_REQUIRED", resourceCulture);
            }
        }
    }
}
