name: Build and Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore CashFlow.sln

      - name: Build solution
        run: dotnet build CashFlow.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test CashFlow.sln --configuration Releas
